### ISSUE TITLE
Merge conflict commited into .zshrc

### ISSUE THREAD

**Issue by captbaritone** [urbanslug/dotfiles#1]
https://github.com/urbanslug/dotfiles/blob/master/.zshrc#L87-L134

**Comment by urbanslug** [comment]
Hello, thanks a ton. This seems to happen more and more the more I use github. Piushing code with conflicts. For example in this situation I have a personal and a master  branch. The personal one is for use locally with passwords and such.

Is there a tool I can use to avoid pushing merge conflicts?

**Comment by captbaritone** [comment]
Hmm. Keeping two different branches with different functionality is hard. I'd look into finding a way to keep the secret information out of version control all together. Maybe you can put them in separate files which are ignored by git via `.gitignore` and then have your committed files source these secret files if they exist?

**Comment by urbanslug** [comment]
Thanks, that's a good idea :smile_cat:
